// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlCRf2C4X9F4QBtwmgs9vNWJeJrQT1jHY',
    appId: '1:793852338308:web:178523b8d57a1ba7c6a2d1',
    messagingSenderId: '793852338308',
    projectId: 'testy-44da4',
    authDomain: 'testy-44da4.firebaseapp.com',
    storageBucket: 'testy-44da4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6WQQuXubTWmcEFN_5sGXS5epH4b5hEeg',
    appId: '1:793852338308:android:34b75fd3e4e8caa0c6a2d1',
    messagingSenderId: '793852338308',
    projectId: 'testy-44da4',
    storageBucket: 'testy-44da4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9QUW6XGw9nmOgakySjY6ZOd3x92190ds',
    appId: '1:793852338308:ios:6ee881dbbf32759fc6a2d1',
    messagingSenderId: '793852338308',
    projectId: 'testy-44da4',
    storageBucket: 'testy-44da4.appspot.com',
    iosBundleId: 'com.example.testy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9QUW6XGw9nmOgakySjY6ZOd3x92190ds',
    appId: '1:793852338308:ios:6ee881dbbf32759fc6a2d1',
    messagingSenderId: '793852338308',
    projectId: 'testy-44da4',
    storageBucket: 'testy-44da4.appspot.com',
    iosBundleId: 'com.example.testy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlCRf2C4X9F4QBtwmgs9vNWJeJrQT1jHY',
    appId: '1:793852338308:web:61f83fc06a6b7508c6a2d1',
    messagingSenderId: '793852338308',
    projectId: 'testy-44da4',
    authDomain: 'testy-44da4.firebaseapp.com',
    storageBucket: 'testy-44da4.appspot.com',
  );
}
